//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MindCorners.Common.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GridState
    {
        public System.Guid Id { get; set; }
        public System.Guid UserId { get; set; }
        public int ModuleId { get; set; }
        public string LayoutData { get; set; }
        public bool ShowFilter { get; set; }
        public string Filter { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
