// <auto-generated />
namespace MindCorners.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Initiallize2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initiallize2));
        
        string IMigrationMetadata.Id
        {
            get { return "201705101003093_Initiallize2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
